lustre-disk-usage.exe: lustre-disk-usage.cpp
	module load gnu/9.2.0 ; \
	g++ --version ; \
	g++ -std=gnu++11 -Wall -W -fpermissive -O3 -g lustre-disk-usage.cpp -o lustre-disk-usage.exe -lz -llustreapi
